- type: gameMap
  id: Meta
  mapName: 'Meta Station'
  mapPath: /Maps/meta.yml
  minPlayers: 50
  stations:
    Meta:
      mapNameTemplate: '{0} Meta Station {1}'
      emergencyShuttlePath: /Maps/Shuttles/emergency_courser.yml
      nameGenerator:
        !type:NanotrasenNameGenerator
        prefixCreator: 'TG'
      overflowJobs:
        - Passenger
      availableJobs:
        Passenger: [ -1, -1 ]
