- type: job
  id: Pilot
  name: job-name-pilot
  playTimeTracker: JobPilot
  startingGear: PilotGear
  icon: "JobIconCaptain"
  supervisors: job-supervisors-captain
  setPreference: true
  accessGroups:
    - AllAccess
  requirements:
    - !type:RoleTimeRequirement
      role: JobEkrixiCommandWhitelist
      time: 1

- type: startingGear
  id: PilotGear
  equipment:
    jumpsuit: ClothingShirtPilot
    lowerClothing: ClothingPantsPilot
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorWhite
    eyes: ClothingEyesGlassesPilot
    id: PilotPDA
    ears: ClothingHeadsetAltCommand
    pocket1: WeaponRevolverDeckard
  innerClothingSkirt: ClothingPantsPilot
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
