- type: guideEntry
  id: Security
  name: guide-entry-security
  text: "/ServerInfo/Guidebook/Security/Security.xml"
  children:
    - Defusal
    - GunsAndYou
    - Law

- type: guideEntry
  id: Defusal
  name: guide-entry-defusal
  text: "/ServerInfo/Guidebook/Security/Defusal.xml"

- type: guideEntry
  id: GunsAndYou
  name: guide-entry-guns-and-you
  text: "/ServerInfo/Guidebook/Security/GunsAndYou.xml"

- type: guideEntry
  id: Law
  name: guide-entry-law
  text: "/ServerInfo/Guidebook/Security/Law.xml"
